#!/bin/bash
cd "$(dirname "$0")"

cd phase3

# echo "compiling to .class"
javac $(find ./* | grep .java)

# echo "compiling to .jar"
cd ..
jar cfm Group26.jar phase3/MANIFEST.txt $(find ./* | grep .class)

# echo "deleting .class files"
cd phase3
rm $(find ./* | grep .class)

# echo "running jar"
cd ..
java -jar Group26.jar